#!/bin/bash

function populate_ext4()
{
	local dev="$1"
	local size="$2"
	local dir="$(mktemp -d)"

	mount $dev $dir
	fallocate --length $size $dir/filler
	umount $dir
	rmdir $dir
}


for i in $(enum 8 15); do
	fallocate -l 1G disk$i
	losetup /dev/loop$i disk$i
	chown flatcap.flatcap disk$i
done

pvcreate /dev/loop{8,9,10,11,12,13,14,15}

vgcreate bigvol /dev/loop{8,9,10,11,12,13,14,15}

lvcreate bigvol -i 2 -m 3 --name bob --size 320M

mke2fs -t ext4 -L bigvol_bob /dev/bigvol/bob

populate_ext4 /dev/bigvol/bob 250M

