#!/bin/bash

IMAGE3="disk3"

function populate_ext4()
{
	local dev="$1"
	local size="$2"
	local dir="$(mktemp -d)"

	mount $dev $dir
	fallocate --length $size $dir/filler
	umount $dir
	rmdir $dir
}


rm -f $IMAGE3

fallocate --length 200M $IMAGE3

losetup /dev/loop3 $IMAGE3

pvcreate /dev/loop3

vgcreate shuffle /dev/loop3

lvcreate --size 52m --name data  shuffle
lvcreate --size 52m --name junk1 shuffle
lvcreate --size 52m --name junk2 shuffle
lvcreate --size 40m --name junk3 shuffle

lvremove -f /dev/shuffle/junk2
lvextend --size +52m /dev/shuffle/data
lvremove -f /dev/shuffle/junk1
lvextend --size +52m /dev/shuffle/data
lvremove -f /dev/shuffle/junk3
lvextend --size +40m /dev/shuffle/data

mke2fs -t ext4 -L shuffle_data /dev/shuffle/data

lvs --all -o lv_name,vg_name,lv_attr,lv_size,lv_uuid,lv_path,lv_kernel_major,lv_kernel_minor,seg_count shuffle

populate_ext4 /dev/shuffle/data 100M

du -sh $IMAGE3

chown flatcap.flatcap $IMAGE3

